// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/gopher-stamp-crud/internal/domain/repository/stamp_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "2025_gopher_StampRally/services/gopher-stamp-crud/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStampRepository is a mock of StampRepository interface.
type MockStampRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStampRepositoryMockRecorder
}

// MockStampRepositoryMockRecorder is the mock recorder for MockStampRepository.
type MockStampRepositoryMockRecorder struct {
	mock *MockStampRepository
}

// NewMockStampRepository creates a new mock instance.
func NewMockStampRepository(ctrl *gomock.Controller) *MockStampRepository {
	mock := &MockStampRepository{ctrl: ctrl}
	mock.recorder = &MockStampRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStampRepository) EXPECT() *MockStampRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockStampRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockStampRepositoryMockRecorder) Count(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockStampRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockStampRepository) Create(ctx context.Context, stamp *entity.Stamp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStampRepositoryMockRecorder) Create(ctx, stamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStampRepository)(nil).Create), ctx, stamp)
}

// Delete mocks base method.
func (m *MockStampRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStampRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStampRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockStampRepository) FindAll(ctx context.Context, limit, offset int) ([]entity.Stamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Stamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockStampRepositoryMockRecorder) FindAll(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockStampRepository)(nil).FindAll), ctx, limit, offset)
}

// FindByID mocks base method.
func (m *MockStampRepository) FindByID(ctx context.Context, id uint) (*entity.Stamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Stamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStampRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStampRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockStampRepository) Update(ctx context.Context, stamp *entity.Stamp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, stamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStampRepositoryMockRecorder) Update(ctx, stamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStampRepository)(nil).Update), ctx, stamp)
}
