// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/gopher-stamp-crud/internal/domain/repository/user_stamp_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "2025_gopher_StampRally/services/gopher-stamp-crud/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserStampRepository is a mock of UserStampRepository interface.
type MockUserStampRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserStampRepositoryMockRecorder
}

// MockUserStampRepositoryMockRecorder is the mock recorder for MockUserStampRepository.
type MockUserStampRepositoryMockRecorder struct {
	mock *MockUserStampRepository
}

// NewMockUserStampRepository creates a new mock instance.
func NewMockUserStampRepository(ctrl *gomock.Controller) *MockUserStampRepository {
	mock := &MockUserStampRepository{ctrl: ctrl}
	mock.recorder = &MockUserStampRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStampRepository) EXPECT() *MockUserStampRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserStampRepository) Create(ctx context.Context, userStamp *entity.UserStamp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userStamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserStampRepositoryMockRecorder) Create(ctx, userStamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserStampRepository)(nil).Create), ctx, userStamp)
}

// ExistsByUserIDAndStampID mocks base method.
func (m *MockUserStampRepository) ExistsByUserIDAndStampID(ctx context.Context, userID, stampID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUserIDAndStampID", ctx, userID, stampID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUserIDAndStampID indicates an expected call of ExistsByUserIDAndStampID.
func (mr *MockUserStampRepositoryMockRecorder) ExistsByUserIDAndStampID(ctx, userID, stampID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUserIDAndStampID", reflect.TypeOf((*MockUserStampRepository)(nil).ExistsByUserIDAndStampID), ctx, userID, stampID)
}

// FindByUserID mocks base method.
func (m *MockUserStampRepository) FindByUserID(ctx context.Context, userID uint) ([]entity.UserStamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.UserStamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserStampRepositoryMockRecorder) FindByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserStampRepository)(nil).FindByUserID), ctx, userID)
}
