// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire_server

import (
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/domain/repository"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/infrastructure/mysql"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/interface/handler"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/usecase"
	openapi "2025_gopher_StampRally/services/gopher-stamp-crud/swagger"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeServer initializes all dependencies and returns a gin.Engine
func InitializeServer() (*gin.Engine, error) {
	db, err := mysql.NewMySQLClient()
	if err != nil {
		return nil, err
	}
	userRepository := NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userStampRepository := NewUserStampRepository(db)
	stampRepository := NewStampRepository(db)
	userStampUseCase := usecase.NewUserStampUseCase(userStampRepository, userRepository, stampRepository)
	stampUseCase := usecase.NewStampUseCase(stampRepository)
	stampHandler := handler.NewStampHandler(stampUseCase)
	userStampHandler := handler.NewUserStampHandler(userStampUseCase)
	serverInterface := handler.NewUserHandler(userUsecase, userStampUseCase, stampHandler, userStampHandler)
	engine := NewGinEngine(serverInterface)
	return engine, nil
}

// wire.go:

// ProviderSet is the set of providers for dependency injection
var ProviderSet = wire.NewSet(mysql.NewMySQLClient, NewUserRepository,
	NewStampRepository,
	NewUserStampRepository, usecase.NewUserUsecase, usecase.NewStampUseCase, usecase.NewUserStampUseCase, handler.NewStampHandler, handler.NewUserStampHandler, handler.NewUserHandler,
)

// NewUserRepository creates a UserRepository interface from mysql implementation
func NewUserRepository(db *gorm.DB) repository.UserRepository {
	return mysql.NewUserRepository(db)
}

// NewStampRepository creates a StampRepository interface from mysql implementation
func NewStampRepository(db *gorm.DB) repository.StampRepository {
	return mysql.NewStampRepository(db)
}

// NewUserStampRepository creates a UserStampRepository interface from mysql implementation
func NewUserStampRepository(db *gorm.DB) repository.UserStampRepository {
	return mysql.NewUserStampRepository(db)
}

// NewGinEngine creates a new gin.Engine with handlers registered
func NewGinEngine(h openapi.ServerInterface) *gin.Engine {
	r := gin.Default()

	corsConfig := cors.DefaultConfig()
	corsConfig.AllowOrigins = []string{
		"http://localhost:3000",
	}
	corsConfig.AllowCredentials = true
	corsConfig.AllowMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	corsConfig.AllowHeaders = []string{"Origin", "Content-Type", "Accept", "Authorization"}
	r.Use(cors.New(corsConfig))

	healthHandler := func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "ok",
		})
	}
	r.GET("/health", healthHandler)
	r.HEAD("/health", healthHandler)
	openapi.RegisterHandlers(r, h)
	return r
}
