// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire_server/cmd/wire_server
//go:build !wireinject
// +build !wireinject

package wire_server

import (
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/domain/repository"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/infrastructure/mysql"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/interface/handler"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/usecase"
	"2025_gopher_StampRally/services/gopher-stamp-crud/swagger"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire_server.go:

// InitializeServer initializes all dependencies and returns a gin.Engine
func InitializeServer() (*gin.Engine, error) {
	db, err := mysql.NewMySQLClient()
	if err != nil {
		return nil, err
	}
	userRepository := NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	serverInterface := handler.NewUserHandler(userUsecase)
	engine := NewGinEngine(serverInterface)
	return engine, nil
}

// wire_server.go:

// ProviderSet is the set of providers for dependency injection
var ProviderSet = wire.NewSet(mysql.NewMySQLClient, NewUserRepository, usecase.NewUserUsecase, handler.NewUserHandler)

// NewUserRepository creates a UserRepository interface from mysql implementation
func NewUserRepository(db *gorm.DB) repository.UserRepository {
	return mysql.NewUserRepository(db)
}

// NewGinEngine creates a new gin.Engine with handlers registered
func NewGinEngine(h openapi.ServerInterface) *gin.Engine {
	r := gin.Default()
	openapi.RegisterHandlers(r, h)
	return r
}
