// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire_server

import (
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/domain/repository"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/infrastructure/mysql"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/interface/handler"
	"2025_gopher_StampRally/services/gopher-stamp-crud/internal/usecase"
	"2025_gopher_StampRally/services/gopher-stamp-crud/swagger"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
	"os"
)

// Injectors from wire.go:

// InitializeServer initializes all dependencies and returns a gin.Engine
func InitializeServer() (*gin.Engine, error) {
	db, err := mysql.NewMySQLClient()
	if err != nil {
		return nil, err
	}
	userRepository := NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userStampRepository := NewUserStampRepository(db)
	stampRepository := NewStampRepository(db)
	userStampUseCase := usecase.NewUserStampUseCase(userStampRepository, userRepository, stampRepository)
	stampUseCase := usecase.NewStampUseCase(stampRepository)
	stampHandler := handler.NewStampHandler(stampUseCase)
	userStampHandler := handler.NewUserStampHandler(userStampUseCase)
	serverInterface := handler.NewUserHandler(userUsecase, userStampUseCase, stampHandler, userStampHandler)
	engine := NewGinEngine(serverInterface)
	return engine, nil
}

// wire.go:

// ProviderSet is the set of providers for dependency injection
var ProviderSet = wire.NewSet(mysql.NewMySQLClient, NewUserRepository,
	NewStampRepository,
	NewUserStampRepository, usecase.NewUserUsecase, usecase.NewStampUseCase, usecase.NewUserStampUseCase, handler.NewStampHandler, handler.NewUserStampHandler, handler.NewUserHandler,
)

// NewUserRepository creates a UserRepository interface from mysql implementation
func NewUserRepository(db *gorm.DB) repository.UserRepository {
	return mysql.NewUserRepository(db)
}

// NewStampRepository creates a StampRepository interface from mysql implementation
func NewStampRepository(db *gorm.DB) repository.StampRepository {
	return mysql.NewStampRepository(db)
}

// NewUserStampRepository creates a UserStampRepository interface from mysql implementation
func NewUserStampRepository(db *gorm.DB) repository.UserStampRepository {
	return mysql.NewUserStampRepository(db)
}

// NewGinEngine creates a new gin.Engine with handlers registered
func NewGinEngine(h openapi.ServerInterface) *gin.Engine {
	r := gin.Default()

	allowedOrigin := os.Getenv("CORS_ALLOWED_ORIGIN")
	if allowedOrigin == "" {
		allowedOrigin = "https://2025-gopher-stamp-rally.vercel.app"
	}
	corsConfig := cors.Config{
		AllowOrigins:     []string{allowedOrigin},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Accept", "Authorization", "X-Requested-With"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * 60 * 60,
	}
	r.Use(cors.New(corsConfig))
	gin.SetMode(gin.ReleaseMode)

	healthHandler := func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "ok",
		})
	}
	r.GET("/health", healthHandler)
	r.HEAD("/health", healthHandler)

	baseURL := os.Getenv("BASE_API_URL")
	options := openapi.GinServerOptions{
		BaseURL: baseURL,
	}
	openapi.RegisterHandlersWithOptions(r, h, options)
	return r
}
