// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// AcquireStampRequest defines model for AcquireStampRequest.
type AcquireStampRequest struct {
	// Otp ワンタイムトークン（4桁の数字）
	Otp string `json:"otp"`

	// StampId 取得するスタンプのID
	StampId int64 `json:"stamp_id"`
}

// Error defines model for Error.
type Error struct {
	// Code エラーコード
	Code string `json:"code"`

	// Details エラー詳細
	Details *string `json:"details,omitempty"`

	// Message エラーメッセージ
	Message string `json:"message"`
}

// Stamp defines model for Stamp.
type Stamp struct {
	// Id スタンプID
	Id int64 `json:"id"`

	// Name スタンプ名
	Name string `json:"name"`
}

// StampCreateRequest defines model for StampCreateRequest.
type StampCreateRequest struct {
	// Name スタンプ名
	Name string `json:"name"`
}

// StampUpdateRequest スタンプ更新リクエスト。
type StampUpdateRequest struct {
	// Name スタンプ名
	Name *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt 作成日時
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FavoriteGoFeature 好きなGoの特徴
	FavoriteGoFeature *string `json:"favorite_go_feature,omitempty"`

	// Icon アイコン画像URL
	Icon *string `json:"icon,omitempty"`

	// Id ユーザーID
	Id int64 `json:"id"`

	// Name ユーザー名
	Name string `json:"name"`

	// TwitterId TwitterID
	TwitterId *string `json:"twitter_id,omitempty"`

	// UpdatedAt 更新日時
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	// FavoriteGoFeature 好きなGoの特徴
	FavoriteGoFeature *string `json:"favorite_go_feature,omitempty"`

	// Icon アイコン画像URL
	Icon *string `json:"icon,omitempty"`

	// Name ユーザー名
	Name string `json:"name"`

	// TwitterId TwitterID
	TwitterId *string `json:"twitter_id,omitempty"`
}

// UserDetail defines model for UserDetail.
type UserDetail struct {
	// AcquiredStamps 取得済みスタンプの一覧
	AcquiredStamps *[]UserStamp `json:"acquired_stamps,omitempty"`

	// CreatedAt 作成日時
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FavoriteGoFeature 好きなGoの特徴
	FavoriteGoFeature *string `json:"favorite_go_feature,omitempty"`

	// Icon アイコン画像URL
	Icon *string `json:"icon,omitempty"`

	// Id ユーザーID
	Id int64 `json:"id"`

	// Name ユーザー名
	Name string `json:"name"`

	// TwitterId TwitterID
	TwitterId *string `json:"twitter_id,omitempty"`

	// UpdatedAt 更新日時
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UserStamp defines model for UserStamp.
type UserStamp struct {
	// AcquiredAt スタンプ取得日時
	AcquiredAt *time.Time `json:"acquired_at,omitempty"`

	// StampId スタンプID
	StampId int64 `json:"stamp_id"`

	// UserId ユーザーID
	UserId int64 `json:"user_id"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	// FavoriteGoFeature 好きなGoの特徴
	FavoriteGoFeature *string `json:"favorite_go_feature,omitempty"`

	// Icon アイコン画像URL
	Icon *string `json:"icon,omitempty"`

	// Name ユーザー名
	Name *string `json:"name,omitempty"`

	// TwitterId TwitterID
	TwitterId *string `json:"twitter_id,omitempty"`
}

// ListStampsParams defines parameters for ListStamps.
type ListStampsParams struct {
	// Limit 取得する件数の上限
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset スキップする件数
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateStampJSONRequestBody defines body for CreateStamp for application/json ContentType.
type CreateStampJSONRequestBody = StampCreateRequest

// UpdateStampJSONRequestBody defines body for UpdateStamp for application/json ContentType.
type UpdateStampJSONRequestBody = StampUpdateRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdateRequest

// AcquireStampJSONRequestBody defines body for AcquireStamp for application/json ContentType.
type AcquireStampJSONRequestBody = AcquireStampRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// スタンプ一覧取得
	// (GET /stamps)
	ListStamps(c *gin.Context, params ListStampsParams)
	// スタンプ作成
	// (POST /stamps)
	CreateStamp(c *gin.Context)
	// スタンプ削除
	// (DELETE /stamps/{id})
	DeleteStamp(c *gin.Context, id int64)
	// スタンプ詳細取得
	// (GET /stamps/{id})
	GetStamp(c *gin.Context, id int64)
	// スタンプ更新
	// (PUT /stamps/{id})
	UpdateStamp(c *gin.Context, id int64)
	// スタンプのOTPを取得
	// (GET /stamps/{id}/otp)
	GetStampOTP(c *gin.Context, id int64)
	// ユーザー一覧取得
	// (GET /users)
	ListUsers(c *gin.Context)
	// ユーザー作成
	// (POST /users)
	CreateUser(c *gin.Context)
	// ユーザー詳細取得
	// (GET /users/{id})
	GetUser(c *gin.Context, id int64)
	// ユーザー更新
	// (PUT /users/{id})
	UpdateUser(c *gin.Context, id int64)
	// ユーザーの取得済みスタンプ一覧取得
	// (GET /users/{id}/stamps)
	ListUserStamps(c *gin.Context, id int64)
	// ユーザーがスタンプを取得
	// (POST /users/{id}/stamps)
	AcquireStamp(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListStamps operation middleware
func (siw *ServerInterfaceWrapper) ListStamps(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStampsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListStamps(c, params)
}

// CreateStamp operation middleware
func (siw *ServerInterfaceWrapper) CreateStamp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStamp(c)
}

// DeleteStamp operation middleware
func (siw *ServerInterfaceWrapper) DeleteStamp(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteStamp(c, id)
}

// GetStamp operation middleware
func (siw *ServerInterfaceWrapper) GetStamp(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStamp(c, id)
}

// UpdateStamp operation middleware
func (siw *ServerInterfaceWrapper) UpdateStamp(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStamp(c, id)
}

// GetStampOTP operation middleware
func (siw *ServerInterfaceWrapper) GetStampOTP(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStampOTP(c, id)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUser(c, id)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, id)
}

// ListUserStamps operation middleware
func (siw *ServerInterfaceWrapper) ListUserStamps(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUserStamps(c, id)
}

// AcquireStamp operation middleware
func (siw *ServerInterfaceWrapper) AcquireStamp(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcquireStamp(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/stamps", wrapper.ListStamps)
	router.POST(options.BaseURL+"/stamps", wrapper.CreateStamp)
	router.DELETE(options.BaseURL+"/stamps/:id", wrapper.DeleteStamp)
	router.GET(options.BaseURL+"/stamps/:id", wrapper.GetStamp)
	router.PUT(options.BaseURL+"/stamps/:id", wrapper.UpdateStamp)
	router.GET(options.BaseURL+"/stamps/:id/otp", wrapper.GetStampOTP)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
	router.GET(options.BaseURL+"/users/:id", wrapper.GetUser)
	router.PUT(options.BaseURL+"/users/:id", wrapper.UpdateUser)
	router.GET(options.BaseURL+"/users/:id/stamps", wrapper.ListUserStamps)
	router.POST(options.BaseURL+"/users/:id/stamps", wrapper.AcquireStamp)
}
